### ISSUE TITLE
Ghostwriter 2.1.0 FTBFS with Qt 5.9.5 (as in Ubuntu Bionic 18.04)

### ISSUE THREAD

**Issue by savoury1** [wereturtle/ghostwriter#710]
**Platform:**
 - Ubuntu 18.04 with Qt 5.9.5
 - GNOME desktop environment

**Describe the bug**
 - Fails to build with Qt 5.9.5 due missing conditional in new source file src/statisticsindicator.cpp
 - Following error is given by GCC before compilation fails:
```
error: ‘const class QFontMetrics’ has no member named ‘horizontalAdvance’
```

**To Reproduce**
1. Attempt to build ghostwriter 2.1.0 against Qt 5.9.5
2. Observe the above quoted error and build failure

**Expected behavior**
Expect the build to complete successfully with Qt 5.9.5 as with earlier Ghostwriter versions.

**Proposed fix**
Attached patch file fixes the build with Qt 5.9.5 as can be seen in this Launchpad build:
https://launchpad.net/~savoury1/+archive/ubuntu/backports/+build/22978957

Patch: [fix-build-for-older-qt.zip](https://github.com/wereturtle/ghostwriter/files/7765263/fix-build-for-older-qt.zip)
