### ISSUE TITLE
QT5 build fails due to QT6 method call

### ISSUE THREAD

**Issue by aichingm** [wereturtle/ghostwriter#800]
**Platform (please complete the following information):**
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: None
 - If Linux, display server [Wayland or X11]: Headless

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: git master ([f3bb949](https://github.com/wereturtle/ghostwriter/commit/f3bb9495523e6f98a9cf9bfd957b7e6a6a949048))
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: private build

**Describe the bug**
Building with qt5 fails with:

```
...
src/stylesheetbuilder.cpp:286:37: error: ‘class QVariant’ has no member named ‘typeId’; did you mean ‘type’?
  286 |     if (QMetaType::QString == value.typeId()) {
      |                                     ^~~~~~
      |                                     type
src/stylesheetbuilder.cpp:289:41: error: ‘class QVariant’ has no member named ‘typeId’; did you mean ‘type’?
  289 |     else if (QMetaType::QColor == value.typeId()) {
      |                                         ^~~~~~
      |                                         type
...
```

`typeId` is not a method of `QVariant` in qt5 (https://doc.qt.io/qt-5/qvariant.html) but only in qt6 (https://doc.qt.io/qt-6/qvariant.html)

This change seams to has been introduced in 50c119aa8f30967213305d242cae1bb6facf8ba3

Does ghostwriter drop qt5 in favor of qt6?

**To Reproduce**
1. `git clone https://github.com/wereturtle/ghostwriter.git`
2. `cd ghostwriter`
3. `qmake`
4. `make`

**Expected behavior**
Build not failing

**Screenshots**
See Code above

**Additional context**
Linux: Archlinux
QT version (qt-base): 5.15.5
qmake: 3.1
make: GNU Make 4.3

**Comment by wereturtle** [comment]
Fixed in a recent commit.  Sorry about the mess.  Things on the master branch are in progress right now.  Ideally, the AUR build should be using a tagged release from the master, and not the latest commit.  Unfortunately, I am not the maintainer for the AUR build and have no control over that.
